[tests-only] Add more test coverage to apiCustomGroups
owncloud/customgroups pull request #427
Opened 2021-05-25 05:28 UTC by SwikritiT

This PR adds more test coverage to apiCustomGroups

2021-05-25 05:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/customgroups?pullRequest=427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/customgroups?pullRequest=427) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/customgroups?pullRequest=427) it.</sub>

2021-05-25 05:43 UTC, kiranparajuli589 commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +    And the HTTP status code should be "200"
```suggestion

```

2021-05-25 06:52 UTC, kiranparajuli589 commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +    Then the HTTP status code should be "200"
check `ocs` code here too

2021-05-25 06:56 UTC, kiranparajuli589 commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +    When user "Alice" shares folder "/foldertoshare" with user "Carol" using the sharing API
```suggestion
    When user "Brian" shares folder "/foldertoshare" with user "Carol" using the sharing API
```
scenario description suggests resharing a received share, but Alice is the file owner

2021-05-25 07:51 UTC, dpakach requested changes

2021-05-25 07:51 UTC, dpakach commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +    And the HTTP status code should be "200"
for these tests I think you should also check if the other users in the groups have access to the files rather than just checking the status codes.

2021-05-25 10:20 UTC, SwikritiT commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +    When user "Alice" shares folder "/foldertoshare" with user "Carol" using the sharing API
A silly mistake thank you for pointing it out

2021-05-26 05:54 UTC, dpakach reviewed
lgtm 👍🏼

2021-05-26 06:15 UTC, dpakach approved these changes

2021-05-28 07:19 UTC, Talank reviewed
LGTM, but it would be better if you fix these spacing

2021-05-28 07:19 UTC, Talank commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +  Scenario:  sharing sub-folder to a normal group when the main folder is already shared with a custom group
```suggestion
  Scenario: sharing sub-folder to a normal group when the main folder is already shared with a custom group
```

2021-05-28 07:19 UTC, Talank commented on tests/acceptance/features/apiCustomGroups/sharingCustomGroups.feature
> +  Scenario:  sharing sub-folder to a custom group when the main folder is already shared with a normal group
```suggestion
  Scenario: sharing sub-folder to a custom group when the main folder is already shared with a normal group
```

2021-05-28 09:18 UTC, phil-davis approved these changes

2021-05-28 09:18 UTC, merged