Tests for inGroupByUri
owncloud/customgroups pull request #612
Opened 2023-11-15 15:03 UTC by IljaN

Tests for #611

2023-11-16 18:52 UTC, DeepDiver1975 requested changes

2023-11-16 18:52 UTC, DeepDiver1975 commented on tests/unit/CustomGroupsDatabaseHandlerTest.php
> +	public function testInGroupByUri() {
php7.4 - use type declarations please

2023-11-16 18:53 UTC, DeepDiver1975 requested changes
.... and conventional commit message is missing ...

2023-11-16 19:30 UTC, jnweiger commented
planned to be included in 10.13.3

2023-11-17 09:27 UTC, IljaN commented
@jnweiger You can proceed with the release as this PR only adds tests.

2023-11-17 12:41 UTC, jnweiger commented
> @jnweiger You can proceed with the release as this PR only adds tests.

agreed. release is done.

2023-11-21 16:29 UTC, DeepDiver1975 requested changes

2023-11-21 16:29 UTC, DeepDiver1975 commented on tests/unit/CustomGroupsDatabaseHandlerTest.php
> +		$this->assertTrue($this->handler->inGroupByUri('user1', 'my_group'));
phpunit assert* methods are static - we should adjust as we touch code .... THX

2023-11-23 14:10 UTC, DeepDiver1975 approved these changes

2023-11-23 14:11 UTC, merged